### ISSUE TITLE
Unable to find an 'mobileactivation_client_new' in DLL 'imobiledevice

### ISSUE THREAD

**Issue by MoonTechnolabs** [libimobiledevice-win32/imobiledevice-net#38] opened 2018-02-27 09:50 UTC
```
MobileactivationClientHandle activation_client;
MobileactivationError ret = activation.mobileactivation_client_new(deviceHandle, serviceDescriptorHandle, out activation_client);
```
getting an error with Unable to find an entry point named 'mobileactivation_client_new' in DLL 'imobiledevice.

Currently, i'm using version no - 212
Install-Package imobiledevice-net -Version 1.2.1-r212

**Comment by MoonTechnolabs** [comment] 2018-03-06 11:27
@qmfrederik , please share your suggestion regarding this issue.

**Comment by qmfrederik** [comment] 2018-03-06 14:23
The issue is that the `imobiledevice.dll` file which you have doesn't export the `mobileactivation_client_new` entrypoint.

I would need to check, but this is probably because the function declarations in [`mobileactivation.h`](https://github.com/libimobiledevice-win32/libimobiledevice/blob/msvc-master/include/libimobiledevice/mobileactivation.h) are missing the `LIBIMOBILEDEVICE_API_MSC` prefix.

You should be able to try this yourself; if you clone `libimobiledevice` from the libimobiledevice-win32 repo, make the change, compile the dll and copy that to your project folder. I'd be happy to accept a PR 😄 .

**Comment by qmfrederik** [comment] 2018-03-21 15:07
This should be fixed with https://www.nuget.org/packages/imobiledevice-net/1.2.1-r249

**Closed by qmfrederik** 2018-03-21 15:07 UTC
